### ISSUE TITLE
Cannot find module 'svelte/internal'

### ISSUE THREAD

**Issue by kamihouse** [bukalapak/snowboard#120]
When I try to run `./node_modules/snowboard/bin/run html -o dist api.apib` like:

```
testeApib $ node -v
v12.16.2

testeApib $ ./node_modules/snowboard/bin/run lint api.apib
OK

testeApib $ ./node_modules/snowboard/bin/run list api.apib
✔  Input(s) parsed in 40 ms.
 GET     /                 200
 GET     /gists            200
 POST    /gists            201
 GET     /gists/{id}       200
 PATCH   /gists/{id}       200
 DELETE  /gists/{id}       204
 PUT     /gists/{id}/star  204
 DELETE  /gists/{id}/star  204
 GET     /gists/{id}/star  200

testeApib $ ./node_modules/snowboard/bin/run html -o dist api.apib
✔  Input parsed: api.apib in 43 ms.
```

On browser I get the following error: `class App extends !(function webpackMissingModule() { var e = new Error("Cannot find module 'svelte/internal'"); e.code = 'MODULE_NOT_FOUND'; throw e; }`

**Comment by subosito** [comment]
@kamihouse thanks for the report; the root cause of the issue is because of the webpack module resolution issue. I've pushed fixes in `v4.1.5`. Please retry and let me know.

**Comment by n4rq5** [comment]
Sorry but I have exactly the same issues on 4.1.19 and 4.1.20 versions as well.

**Comment by X-Ray-Jin** [comment]
Hey I have the same issue with version 4.1.21

But I am getting this when using the docker image on Windows 10

**Comment by aitor** [comment]
Yep, we can confirm the issue is still present in version 4.1.21 in a Ubuntu build running on Travis.

**Comment by janis-vitols** [comment]
@aitor  @X-Ray-Jin @n4rq5 have you got it somehow solved or using some kind of workaround? Currently trying to migrate from `aglio` to `snowboard` and have the same issue on `Mac (Big Sur)` & `Node v12.20.2`. Blank `index.html` page with the same error `"Cannot find module 'svelte/internal'"`

**Comment by n4rq5** [comment]
@janis-vitols 
After trial and error attempts we discovered the issue was Node v12. Had to downgrade to v10 to make it work.

**Comment by janis-vitols** [comment]
@n4rq5 thanks. Downgraded to `v10.23.3`, generated HTML files, but unfortunately got the same error :/

**Comment by janis-vitols** [comment]
Couldn't figure out how to get this working, as a result, switched to `redoc`.

**Comment by X-Ray-Jin** [comment]
Thanks for your replies. In the end we've found an alternative and are now using the Apiary CLI https://help.apiary.io/tools/apiary-cli/
